### ISSUE TITLE
Adding city endpoint

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/spark-18#2]
Create a new endpoint called City with the following values:
City Name
Venue
Time
Venue Link(Is a google maps link)
Capacity(optional)
no. of people registered
boolean variable **active** - To check if the city can accept registrations. Leave the part to edit the registration form, i'll assign it to another coord.

And create a route which can be accessed by admin alone, The page has the following tabs within the same route.
1. Add a city - Create a new city with the above said properties
2. Edit a city - Edit the details of an existing city
3. Close registrations - Choose a city and close registrations should make the **active** variable false.

Hope this is clear. Call/Ping me if you have any doubts regarding this.

Acknowledge below in the comment.

**Comment by Rohithram** [comment]
acknowledged

**Comment by Rohithram** [comment]
tabs in the sense inside the route we should have three tabs or in main page itself should it be there if admin logs in

**Comment by gokulan97** [comment]
Any UI da. Which somehow has all the mentioned details.

On Jul 15, 2017 11:24 PM, "Rohithram R" <notifications@github.com> wrote:

tabs in the sense inside the route we should have three tabs or in main
page itself should it be there if admin logs in

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ShaastraWebops/spark-18/issues/2#issuecomment-315550998>,
or mute the thread

**Comment by gokulan97** [comment]
Closed.
